"""phase 1 initial schema (entities, observations, recommendations, audit_log)

Revision ID: 61ed19968491
Revises: 
Create Date: 2026-05-07 21:56:53.997220+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

import geoalchemy2  # noqa: F401  (Alembic-rendered Geometry types reference this module)
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61ed19968491'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostGIS is required for the geometry(POINT, 4326) columns. Idempotent —
    # safe to run on Neon, Supabase, or self-hosted Postgres so long as the
    # role can create extensions in the current database.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('self_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('prev_hash', name='audit_log_prev_hash_unique'),
    sa.UniqueConstraint('self_hash', name='audit_log_self_hash_unique')
    )
    op.create_index('ix_audit_log_actor', 'audit_log', ['actor'], unique=False)
    op.create_index('ix_audit_log_t', 'audit_log', ['t'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.CheckConstraint("domain IN ('maritime', 'wildfire', 'anti_poaching', 'wilderness_sar', 'amber', 'humanitarian', 'flood', 'cross')", name='entities_domain_check'),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index('ix_entities_domain_type', 'entities', ['domain', 'type'], unique=False)
    op.create_index('ix_entities_geom', 'entities', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_entities_last_seen', 'entities', ['last_seen'], unique=False)
    op.create_index('ix_entities_priority', 'entities', ['priority_score'], unique=False)
    op.create_table('observations',
    sa.Column('obs_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('h3_cell', sa.String(length=20), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_lineage', sa.String(), nullable=True),
    sa.CheckConstraint("domain IN ('maritime', 'wildfire', 'anti_poaching', 'wilderness_sar', 'amber', 'humanitarian', 'flood', 'cross')", name='observations_domain_check'),
    sa.PrimaryKeyConstraint('obs_id')
    )
    op.create_index('ix_observations_geom', 'observations', ['geom'], unique=False, postgresql_using='gist')
    op.create_index('ix_observations_source', 'observations', ['source'], unique=False)
    op.create_index('ix_observations_t', 'observations', ['t'], unique=False)
    op.create_table('entity_observations',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('obs_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obs_id'], ['observations.obs_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', 'obs_id')
    )
    op.create_table('recommendations',
    sa.Column('rec_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('suggested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.String(), nullable=True),
    sa.CheckConstraint("decision IN ('pending','approved','rejected')", name='recommendations_decision_check'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index('ix_recommendations_decision', 'recommendations', ['decision'], unique=False)
    op.create_index('ix_recommendations_entity', 'recommendations', ['entity_id'], unique=False)
    op.create_table('recommendation_evidence',
    sa.Column('rec_id', sa.String(), nullable=False),
    sa.Column('obs_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['obs_id'], ['observations.obs_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rec_id'], ['recommendations.rec_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rec_id', 'obs_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_evidence')
    op.drop_index('ix_recommendations_entity', table_name='recommendations')
    op.drop_index('ix_recommendations_decision', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('entity_observations')
    op.drop_index('ix_observations_t', table_name='observations')
    op.drop_index('ix_observations_source', table_name='observations')
    op.drop_index('ix_observations_geom', table_name='observations', postgresql_using='gist')
    op.drop_table('observations')
    op.drop_index('ix_entities_priority', table_name='entities')
    op.drop_index('ix_entities_last_seen', table_name='entities')
    op.drop_index('ix_entities_geom', table_name='entities', postgresql_using='gist')
    op.drop_index('ix_entities_domain_type', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_audit_log_t', table_name='audit_log')
    op.drop_index('ix_audit_log_actor', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
