"""add archive_state table

Revision ID: c791f9e96d69
Revises: 61ed19968491
Create Date: 2026-05-08 03:01:26.750924+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c791f9e96d69'
down_revision: Union[str, Sequence[str], None] = '61ed19968491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_state',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('last_archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archive_state')
    # ### end Alembic commands ###
