"""add sar_scenes + sar_detections (phase 4)

Revision ID: 99fec3a702aa
Revises: c791f9e96d69
Create Date: 2026-05-08 03:04:55.178886+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

import geoalchemy2  # noqa: F401  (Geometry types in this migration reference it)
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99fec3a702aa'
down_revision: Union[str, Sequence[str], None] = 'c791f9e96d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sar_scenes',
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('sensor_mode', sa.String(length=8), nullable=False),
    sa.Column('polarization', sa.String(length=16), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('footprint', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('raw_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("state IN ('discovered','downloaded','detected','failed')", name='sar_scenes_state_check'),
    sa.PrimaryKeyConstraint('scene_id')
    )
    # GeoAlchemy2 auto-creates idx_sar_scenes_footprint as part of
    # CREATE TABLE; do not add an explicit op.create_index for it.
    op.create_index('ix_sar_scenes_acquired_at', 'sar_scenes', ['acquired_at'], unique=False)
    op.create_index('ix_sar_scenes_state', 'sar_scenes', ['state'], unique=False)
    op.create_table('sar_detections',
    sa.Column('detection_id', sa.String(), nullable=False),
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rcs_db', sa.Float(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('matched_entity_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['matched_entity_id'], ['entities.entity_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['sar_scenes.scene_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detection_id')
    )
    op.create_index('ix_sar_detections_matched', 'sar_detections', ['matched_entity_id'], unique=False)
    op.create_index('ix_sar_detections_scene', 'sar_detections', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sar_detections_scene', table_name='sar_detections')
    op.drop_index('ix_sar_detections_matched', table_name='sar_detections')
    op.drop_table('sar_detections')
    op.drop_index('ix_sar_scenes_state', table_name='sar_scenes')
    op.drop_index('ix_sar_scenes_acquired_at', table_name='sar_scenes')
    # idx_sar_scenes_footprint is dropped automatically by drop_table.
    op.drop_table('sar_scenes')
    # ### end Alembic commands ###
